--Consulta Los 5 proveedores a los cuales más se le compran artículos.
select
PROVEDOR.PROVEEDOR_NOMBRE AS Nombre_Proveedor,
PROVEDOR.PROVEEDOR_PAIS AS Pais,
PROVEDOR.PROVEEDOR_CIUDAD AS Ciudad,
PROVEDOR.PROVEEDOR_DIRECCION AS Direccion,
PROVEDOR.PROVEEDOR_TELEFONO AS Telefono,
PROVEDOR.PROVEEDOR_CORREO AS Correo,
SUM(DETALLE_LOTE.LOTE_DETALLE_CANTIDAD) AS Numero_de_articulos_comprados
FROM PROVEDOR
INNER JOIN LOTE ON LOTE.LOTE_PROVEEDOR=PROVEDOR.PROVEEDOR_CODIGO
INNER JOIN DETALLE_LOTE ON DETALLE_LOTE.LOTE_CODIGO=LOTE.LOTE_CODIGO
GROUP BY 
Nombre_Proveedor,
Pais,
Ciudad,
Direccion,
Telefono,
Correo
ORDER BY SUM(DETALLE_LOTE.LOTE_DETALLE_CANTIDAD) DESC
FETCH FIRST 5 ROWS ONLY


--Consulta Los 5 productos/artículo más vendidos.
select
PRODUCTOS.PRODUCTOS_DESCRIPCION AS Articulo,
CATEGORIA.CATEGORIA_NOMBRE AS Categoria,
MARCA.MARCA_NOMBRE AS Marca,
PRODUCTOS.PRODUCTOS_PRECIO_UNITARIO AS Precio,
SUM(DETALLE_FACTURA.DETALLE_FACTURA_CANTIDAD) AS Numero_de_articulos_vendidos
FROM PRODUCTOS
INNER JOIN MARCA ON PRODUCTOS.MARCA_CODIGO=MARCA.MARCA_CODIGO
INNER JOIN CATEGORIA ON  PRODUCTOS.CATEGORIA_CODIGO=CATEGORIA.CATEGORIA_CODIGO
INNER JOIN DETALLE_FACTURA ON DETALLE_FACTURA.PRODUCTOS_CODIGO=PRODUCTOS.PRODUCTOS_CODIGO
GROUP BY
Articulo,
Categoria,
Marca,
Precio
ORDER BY SUM(DETALLE_FACTURA.DETALLE_FACTURA_CANTIDAD) DESC
FETCH FIRST 5 ROWS ONLY

--Consulta los 5 cliente más recurrente.
SELECT 
CLIENTE.CLIENTE_CEDULA AS Cedula,
CLIENTE.CLIENTE_RUC AS Ruc,
CLIENTE.CLIENTE_NOMBRE || ' ' || CLIENTE.CLIENTE_APELLIDO AS Nombre,
TIPO_CLIENTE.TIPO_CLIENTE_NOMBRE AS Tipo_Cliente,
CLIENTE.CLIENTE_DIRECCION AS Dirección,
CLIENTE.CLIENTE_TELEFONO AS Telefono,
CLIENTE.CLIENTE_CORREO AS Correo,
COUNT(FACTURA.FACTURA_CODIGO) AS Numero_de_compras_realizadas
FROM CLIENTE
INNER JOIN TIPO_CLIENTE ON TIPO_CLIENTE.TIPO_CLIENTE_CODIGO=CLIENTE.TIPO_CLIENTE_CODIGO
INNER JOIN FACTURA ON FACTURA.CLIENTE_CEDULA=CLIENTE.CLIENTE_CEDULA
GROUP BY
Cedula,
Nombre,
Tipo_Cliente,
Dirección,
Telefono,
Correo
ORDER BY COUNT(FACTURA.FACTURA_CODIGO) DESC
FETCH FIRST 5 ROWS ONLY


--Consulta Productos que tengan una existencia menor a 15 en el inventario.
select
PRODUCTOS.PRODUCTOS_DESCRIPCION AS Articulo,
CATEGORIA.CATEGORIA_NOMBRE AS Categoria,
MARCA.MARCA_NOMBRE AS Marca,
PRODUCTOS.PRODUCTOS_PRECIO_UNITARIO AS Precio,
SUCURSAL.SUCURSAL_NOMBRE AS Sucursal,
INVENTARIO.INVENTARIO_CANTIDAD_BODEGA AS Existencia_en_bodega
FROM PRODUCTOS
INNER JOIN MARCA ON PRODUCTOS.MARCA_CODIGO=MARCA.MARCA_CODIGO
INNER JOIN CATEGORIA ON  PRODUCTOS.CATEGORIA_CODIGO=CATEGORIA.CATEGORIA_CODIGO
INNER JOIN INVENTARIO ON INVENTARIO.PRODUCTOS_CODIGO=PRODUCTOS.PRODUCTOS_CODIGO
INNER JOIN SUCURSAL ON SUCURSAL.SUCURSAL_CODIGO=INVENTARIO.SUCURSAL_CODIGO
WHERE INVENTARIO.INVENTARIO_CANTIDAD_BODEGA<16
GROUP BY
Articulo,
Categoria,
Marca,
Precio,
Sucursal,
Existencia_en_bodega

